services:
  facefusion-cuda:
    image: 330858616968.dkr.ecr.eu-north-1.amazonaws.com/papyaglobal-dev:latest
    command: [ 'uvicorn', 'api.facefusion:app', '--reload', '--host', '0.0.0.0', '--port', '7860' ]
    env_file:
      - .env
    volumes:
      - .assets:/facefusion/.assets
      - .caches:/facefusion/.caches
      - .jobs:/facefusion/.jobs
    ports:
      - "7870:7860"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu, video ]
