services:
 facefusion-cpu:
  image: 330858616968.dkr.ecr.eu-north-1.amazonaws.com/papyaglobal-dev:latest
  command: [ 'python', 'facefusion.py', 'run' ]
  volumes:
  - .assets:/facefusion/.assets
  - .caches:/facefusion/.caches
  - .jobs:/facefusion/.jobs
  ports:
  - 7865:7860