services:
  facefusion-cuda:
    image: 330858616968.dkr.ecr.eu-north-1.amazonaws.com/papyaglobal-dev:latest
    command: sh -c "cd facefusion && uvicorn api.facefusion:app --host 0.0.0.0 --port 7860 --workers 1 --timeout-keep-alive 1800"
    env_file:
      - .env
    volumes:
      - .assets:/facefusion/.assets
      - .caches:/facefusion/.caches
      - .jobs:/facefusion/.jobs
    ports:
      - "7870:7860"
    logging:
      driver: awslogs
      options:
        awslogs-region: eu-north-1
        awslogs-group: /aws/papya-global-logs
        awslogs-stream: papya-global-log-stream
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu, utility, video]
  
  dcgm_exporter:
    image: nvidia/dcgm-exporter:4.0.0-4.0.1-ubuntu22.04
    restart: unless-stopped
    environment:
      - DCGM_EXPORTER_NO_HOSTNAME=1
    cap_add:
      - SYS_ADMIN
    ports:
      - "9400:9400"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    networks:
      - monitoring
  
  prometheus:
    image: prom/prometheus:latest
    runtime: runc
    ports:
      - "9090:9090"
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.console.libraries=/usr/share/prometheus/console_libraries
      - --web.console.templates=/usr/share/prometheus/consoles
      - --storage.tsdb.wal-compression
      - --storage.tsdb.retention.time=90d
      - --storage.tsdb.retention.size=5GB
    restart: unless-stopped
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    networks:
      - monitoring
  
  grafana:
    image: grafana/grafana:latest
    runtime: runc
    ports:
      - "3000:3000"
    restart: unless-stopped
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin_password
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/etc/grafana/dashboards/node_exporter/node_exporter.json
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/etc/grafana/dashboards
    networks:
      - monitoring
  
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    runtime: runc
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    networks:
      - monitoring
  
  node-exporter:
    image: prom/node-exporter:latest
    runtime: runc
    ports:
      - "9100:9100"
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
      - '--collector.filesystem'
      - '--collector.diskstats'
    networks:
      - monitoring

volumes:
  prometheus_data:
    driver: local
  grafana_data:
    driver: local

networks:
  monitoring:
    driver: bridge
